/**
 * Runtime configuration loaded from /runtime-config.json.
 * Generated by deploy script from CDK backend outputs.
 */

export interface RuntimeConfig {
  userPoolId: string;
  userPoolClientId: string;
  awsRegion: string;
  agentRuntimeArn: string;
}

let _config: RuntimeConfig | null = null;

export async function loadRuntimeConfig(): Promise<RuntimeConfig> {
  if (_config) return _config;

  try {
    const response = await fetch('/runtime-config.json');
    if (response.ok) {
      _config = await response.json();
      return _config!;
    }
  } catch {
    // Fall through to env var fallbacks
  }

  _config = {
    userPoolId: import.meta.env.VITE_COGNITO_USER_POOL_ID ?? '',
    userPoolClientId: import.meta.env.VITE_COGNITO_USER_POOL_CLIENT_ID ?? '',
    awsRegion: import.meta.env.VITE_AWS_REGION ?? 'us-east-1',
    agentRuntimeArn: import.meta.env.VITE_AGENT_RUNTIME_ARN ?? '',
  };
  return _config;
}

export function getRuntimeConfig(): RuntimeConfig {
  if (!_config) {
    throw new Error('Runtime config not loaded. Call loadRuntimeConfig() first.');
  }
  return _config;
}
