/**
 * Runtime configuration loaded from /runtime-config.json.
 *
 * This file is generated by CDK and deployed to S3 alongside the frontend.
 * It contains resource IDs (Cognito pools, agent endpoint, etc.) that are
 * only known after infrastructure deployment.
 *
 * For local development, create a public/runtime-config.json manually or
 * use VITE_* env vars as fallbacks.
 */

export interface RuntimeConfig {
  userPoolId: string;
  userPoolClientId: string;
  identityPoolId: string;
  menuTableName: string;
  awsRegion: string;
  agentEndpointUrl: string;
}

let _config: RuntimeConfig | null = null;

export async function loadRuntimeConfig(): Promise<RuntimeConfig> {
  if (_config) return _config;

  try {
    const response = await fetch('/runtime-config.json');
    if (response.ok) {
      _config = await response.json();
      return _config!;
    }
  } catch {
    // Fall through to env var fallbacks
  }

  // Fallback to Vite env vars (for local development)
  _config = {
    userPoolId: import.meta.env.VITE_COGNITO_USER_POOL_ID ?? '',
    userPoolClientId: import.meta.env.VITE_COGNITO_USER_POOL_CLIENT_ID ?? '',
    identityPoolId: import.meta.env.VITE_COGNITO_IDENTITY_POOL_ID ?? '',
    menuTableName: import.meta.env.VITE_MENU_TABLE_NAME ?? 'DriveThruMenu',
    awsRegion: import.meta.env.VITE_AWS_REGION ?? 'us-east-1',
    agentEndpointUrl: import.meta.env.VITE_AGENT_ENDPOINT ?? '',
  };
  return _config;
}

export function getRuntimeConfig(): RuntimeConfig {
  if (!_config) {
    throw new Error('Runtime config not loaded. Call loadRuntimeConfig() first.');
  }
  return _config;
}
